app:
  port: 8888

db:
  username: DevEtx
  password: Dev2024$$E@Tax
  hostname: 192.168.14.222
  port: 1433
  db: EAVCAX62LIVE

smb:
  hostname: 10.15.5.4
  port: 445
  username: titi.cha
  passwor: For+ever17!
  domain: energyabsolute
